id: P93984874
initial_creation_type: ocr
source_metadata:
  volumes:
    fcb19ffc7c1d4de4b9086e78a2843427:
      base_file: v040.txt
      image_group_id: I1PD95885
      title: རལ་གཅིག་མའི་སྒྲུབ་པའི་ཐབས།
      total_pages: 1648
      volume_number: 40
